In [ ]:
a = [[1, 2],
     [3, 4]]

b = [[5, 6],
     [7, 8]]

# Output should be:
# [[1*5, 2*6],
#  [3*7, 4*8]]
# = [[5,  12],
#   [21, 32]]

In [10]:
import numpy as np
a = np.array([[1, 2],
     [3, 4]])

b = np.array([[5, 6],
     [7, 8]])

print(f"Matrix multiplication:\n{np.matmul(a,b)} \n\n\n Element-wise multiplication : \n{a*b}")

Matrix multiplication:
[[19 22]
 [43 50]] 


 Element-wise multiplication : 
[[ 5 12]
 [21 32]]


In [23]:
# Using For loops
a = [[1, 2],
     [3, 4]]

b = [[5, 6],
     [7, 8]]

# print(a)
# print(len(a))

res = []
for i in range(len(a)):
    temp = []
    for j in range(len(b)):
        temp.append(a[i][j] * b[i][j])
    res.append(temp)

res

[[5, 12], [21, 32]]

In [29]:
#  Using the scatter pattern (indices → updates → scatter)
# 1. Create indices with all possible combinations
# 2. Compute values and store them
# 3. Make output matrix of zeros
# 4. Place each update at its correct (i, j) position in the output matrix
a = [[1, 2],
     [3, 4]]

b = [[5, 6],
     [7, 8]]

# TODO: Step 1: Create indices with all possible combinations
indices = []
for i in range(len(a)):
    for j in range(len(b)):
        indices.append((i,j))
print(f"Indices: {indices}")

# TODO: Step 2. Compute values and store them
updates = []
for i,j in indices:
    updates.append(a[i][j] * b[i][j])
print(f"Updates: {updates}")

# TODO: Step 3. Make output matrix of zeros
output_grid = []
for i in range(len(a)):
    output_grid.append([0]*len(b))    
print(f"output_grid: {output_grid}")


# TODO: Step 4. Place each update at its correct (i, j) position in the output matrix

for idx,(i,j) in enumerate(indices):
    output_grid[i][j] = updates[idx]

print(output_grid)




Indices: [(0, 0), (0, 1), (1, 0), (1, 1)]
Updates: [5, 12, 21, 32]
output_grid: [[0, 0], [0, 0]]
[[5, 12], [21, 32]]


### Matrix Multiplication

In [ ]:
a = [[1, 2],      # 3x2
     [3, 4],
     [5, 6]]

b = [[5, 6, 7],   # 2x3
     [7, 8, 9]]

# Expected output: 3x3

res = []
for i in range(len(a)):
    temp = []
    for j in range(len(b[0])):
        total = 0
        for k in range(len(b)):
            total+=a[i][k] * b[k][j]
        temp.append(total)
    res.append(temp)

res

# Not the best implementation 

[[19, 22, 25], [43, 50, 57], [67, 78, 89]]

In [43]:
mat_a = np.array(a)
mat_b = np.array(b)

mat_a @ mat_b

array([[19, 22, 25],
       [43, 50, 57],
       [67, 78, 89]])

In [44]:

def my_matmal(mat_a,mat_b):
    """Performs matrix multiplication on Python List"""
    a_rows = len(mat_a)
    a_cols = len(mat_a[0])
    b_rows = len(mat_b)
    b_cols = len(mat_b[0])

    shared_dim = b_rows # or a_cols -> Anything works
    if a_cols!=b_rows:
        raise ValueError(f"Shape mismatch! A has {a_cols} cols but B has {b_rows} rows")
    # output_shape = (a_rows,b_cols)
    res = []
    for i in range(a_rows):
        temp = []
        for j in range(b_cols):
            total = 0
            for k in range(shared_dim):
                total+=mat_a[i][k] * mat_b[k][j]
            temp.append(total)
        res.append(temp)
    
    return res
        

In [45]:
# Test 1 — square matrices
A = [[1, 2],
     [3, 4]]
B = [[5, 6],
     [7, 8]]
print(my_matmal(A, B))  # [[19, 22], [43, 50]]

# Test 2 — uneven shapes (3x2) @ (2x3)
A = [[1, 2],
     [3, 4],
     [5, 6]]
B = [[5, 6, 7],
     [7, 8, 9]]
print(my_matmal(A, B))  # [[19, 22, 25], [43, 50, 57], [67, 78, 89]]

# Test 3 — shape mismatch should raise error
A = [[1, 2, 3]]  # 1x3
B = [[1, 2],     # 2x2
     [3, 4]]
print(my_matmal(A, B))  # ValueError!

[[19, 22], [43, 50]]
[[19, 22, 25], [43, 50, 57], [67, 78, 89]]


ValueError: Shape mismatch! A has 3 cols but B has 2 rows

In [ ]:


#**  Using the scatter pattern (indices → updates → scatter)
# 1. Create indices with all possible combinations
# 2. Compute values and store them
# 3. Make output matrix of zeros
# 4. Place each update at its correct (i, j) position in the output matrix



# TODO: Vectorized scatter approach


def my_mat_mal_vec(mat_a,mat_b):

    # TODO: 1. Create indices with all possible combinations

    indices = []

    for i in range(len(mat_a)):
        for j in range(len(mat_b[0])):
            temp = []
            for k in range(len(mat_b)):
                temp.append(((i,k),(k,j)))
            indices.append(temp)
    # print(f"Indices: {indices}")

    # TODO: 2. Compute values and store them
    updates = []
    for idx,pairs in enumerate(indices):
        total = 0
        for pair in pairs:
            i,j = pair[0]
            x,y = pair[1]
            total+=mat_a[i][j] * mat_b[x][y]
        updates.append(total)

    # print(f"updates: {updates}")
        
        
    # TODO: 3. Make output matrix of zeros
    a_rows = len(mat_a)
    b_cols = len(mat_b[0])
    output_grid = [[0] * b_cols for _ in range(a_rows)]
    # print(output_grid)

    # TODO: 4. Place each update at its correct (i, j) position in the output matrix
    count = 0
    for outputs in output_grid:
        for output_loc in range(len(outputs)):
            outputs[output_loc] = updates[count]
            count+=1

    # print(output_grid)

    return output_grid

        


In [67]:
mat_a = [[1, 2],
     [3, 4],
     [5, 6]]
mat_b = [[5, 6, 7],
     [7, 8, 9]]
# [[19, 22, 25], [43, 50, 57], [67, 78, 89]]
my_mat_mal_vec(mat_a,mat_b)

Indices: [[((0, 0), (0, 0)), ((0, 1), (1, 0))], [((0, 0), (0, 1)), ((0, 1), (1, 1))], [((0, 0), (0, 2)), ((0, 1), (1, 2))], [((1, 0), (0, 0)), ((1, 1), (1, 0))], [((1, 0), (0, 1)), ((1, 1), (1, 1))], [((1, 0), (0, 2)), ((1, 1), (1, 2))], [((2, 0), (0, 0)), ((2, 1), (1, 0))], [((2, 0), (0, 1)), ((2, 1), (1, 1))], [((2, 0), (0, 2)), ((2, 1), (1, 2))]]
updates: [19, 22, 25, 43, 50, 57, 67, 78, 89]
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[19, 22, 25], [43, 50, 57], [67, 78, 89]]


[[19, 22, 25], [43, 50, 57], [67, 78, 89]]

In [ ]:
# Better structured code by Claude
def mat_mal_claude(mat_a,mat_b):
    # CHANGE 1: Flat (i,j,k) triplets instead of nested coordinate pairs
    indices = []
    for i in range(len(mat_a)):
        for j in range(len(mat_b[0])):
            for k in range(len(mat_b)):
                indices.append((i, j, k))  # simple triplet, not ((i,k),(k,j))
    print(f"Indices: {indices}")

    # CHANGE 2: No summing here — just one multiplication per triplet
    updates = []
    for i, j, k in indices:
        updates.append(mat_a[i][k] * mat_b[k][j])  # flat list, no total accumulation
    print(f"Updates: {updates}")

    # SAME: output grid of zeros
    a_rows = len(mat_a)
    b_cols = len(mat_b[0])
    output_grid = [[0] * b_cols for _ in range(a_rows)]

    # CHANGE 3: += instead of = (accumulation happens here, not in step 2)
    for idx, (i, j, k) in enumerate(indices):
        output_grid[i][j] += updates[idx]  # += not =

    return output_grid


In [72]:
# Test 2 — uneven shapes (3x2) @ (2x3)
A = [[1, 2], [3, 4], [5, 6]]
B = [[5, 6, 7], [7, 8, 9]]
assert mat_mal_claude(A, B) == [[19, 22, 25], [43, 50, 57], [67, 78, 89]], "Test 2 failed"
print("Test 2 passed — uneven shapes (3x2) @ (2x3)")

Indices: [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (0, 2, 0), (0, 2, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1), (1, 2, 0), (1, 2, 1), (2, 0, 0), (2, 0, 1), (2, 1, 0), (2, 1, 1), (2, 2, 0), (2, 2, 1)]
Updates: [5, 14, 6, 16, 7, 18, 15, 28, 18, 32, 21, 36, 25, 42, 30, 48, 35, 54]
Test 2 passed — uneven shapes (3x2) @ (2x3)


In [70]:
# Test 1 — square matrices
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
assert mat_mal_claude(A, B) == [[19, 22], [43, 50]], "Test 1 failed"
print("Test 1 passed — square matrices")

# Test 2 — uneven shapes (3x2) @ (2x3)
A = [[1, 2], [3, 4], [5, 6]]
B = [[5, 6, 7], [7, 8, 9]]
assert mat_mal_claude(A, B) == [[19, 22, 25], [43, 50, 57], [67, 78, 89]], "Test 2 failed"
print("Test 2 passed — uneven shapes (3x2) @ (2x3)")

# Test 3 — uneven shapes (2x3) @ (3x2)
A = [[1, 2, 3], [4, 5, 6]]
B = [[7, 8], [9, 10], [11, 12]]
assert mat_mal_claude(A, B) == [[58, 64], [139, 154]], "Test 3 failed"
print("Test 3 passed — uneven shapes (2x3) @ (3x2)")

# Test 4 — identity matrix
A = [[1, 2], [3, 4]]
I = [[1, 0], [0, 1]]
assert mat_mal_claude(A, I) == A, "Test 4 failed"
print("Test 4 passed — identity matrix")

# Test 5 — zeros matrix
A = [[1, 2], [3, 4]]
Z = [[0, 0], [0, 0]]
assert mat_mal_claude(A, Z) == [[0, 0], [0, 0]], "Test 5 failed"
print("Test 5 passed — zeros matrix")

# Test 6 — 1x1 matrix
A = [[5]]
B = [[6]]
assert mat_mal_claude(A, B) == [[30]], "Test 6 failed"
print("Test 6 passed — 1x1 matrix")

Indices: [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]
Updates: [5, 14, 6, 16, 15, 28, 18, 32]
Test 1 passed — square matrices
Indices: [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (0, 2, 0), (0, 2, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1), (1, 2, 0), (1, 2, 1), (2, 0, 0), (2, 0, 1), (2, 1, 0), (2, 1, 1), (2, 2, 0), (2, 2, 1)]
Updates: [5, 14, 6, 16, 7, 18, 15, 28, 18, 32, 21, 36, 25, 42, 30, 48, 35, 54]
Test 2 passed — uneven shapes (3x2) @ (2x3)
Indices: [(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2), (1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 1, 0), (1, 1, 1), (1, 1, 2)]
Updates: [7, 18, 33, 8, 20, 36, 28, 45, 66, 32, 50, 72]
Test 3 passed — uneven shapes (2x3) @ (3x2)
Indices: [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]
Updates: [1, 0, 0, 2, 3, 0, 0, 4]
Test 4 passed — identity matrix
Indices: [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1,

In [71]:
# Test 1 — square matrices
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
assert my_mat_mal_vec(A, B) == [[19, 22], [43, 50]], "Test 1 failed"
print("Test 1 passed — square matrices")

# Test 2 — uneven shapes (3x2) @ (2x3)
A = [[1, 2], [3, 4], [5, 6]]
B = [[5, 6, 7], [7, 8, 9]]
assert my_mat_mal_vec(A, B) == [[19, 22, 25], [43, 50, 57], [67, 78, 89]], "Test 2 failed"
print("Test 2 passed — uneven shapes (3x2) @ (2x3)")

# Test 3 — uneven shapes (2x3) @ (3x2)
A = [[1, 2, 3], [4, 5, 6]]
B = [[7, 8], [9, 10], [11, 12]]
assert my_mat_mal_vec(A, B) == [[58, 64], [139, 154]], "Test 3 failed"
print("Test 3 passed — uneven shapes (2x3) @ (3x2)")

# Test 4 — identity matrix
A = [[1, 2], [3, 4]]
I = [[1, 0], [0, 1]]
assert my_mat_mal_vec(A, I) == A, "Test 4 failed"
print("Test 4 passed — identity matrix")

# Test 5 — zeros matrix
A = [[1, 2], [3, 4]]
Z = [[0, 0], [0, 0]]
assert my_mat_mal_vec(A, Z) == [[0, 0], [0, 0]], "Test 5 failed"
print("Test 5 passed — zeros matrix")

# Test 6 — 1x1 matrix
A = [[5]]
B = [[6]]
assert my_mat_mal_vec(A, B) == [[30]], "Test 6 failed"
print("Test 6 passed — 1x1 matrix")

Indices: [[((0, 0), (0, 0)), ((0, 1), (1, 0))], [((0, 0), (0, 1)), ((0, 1), (1, 1))], [((1, 0), (0, 0)), ((1, 1), (1, 0))], [((1, 0), (0, 1)), ((1, 1), (1, 1))]]
updates: [19, 22, 43, 50]
[[0, 0], [0, 0]]
[[19, 22], [43, 50]]
Test 1 passed — square matrices
Indices: [[((0, 0), (0, 0)), ((0, 1), (1, 0))], [((0, 0), (0, 1)), ((0, 1), (1, 1))], [((0, 0), (0, 2)), ((0, 1), (1, 2))], [((1, 0), (0, 0)), ((1, 1), (1, 0))], [((1, 0), (0, 1)), ((1, 1), (1, 1))], [((1, 0), (0, 2)), ((1, 1), (1, 2))], [((2, 0), (0, 0)), ((2, 1), (1, 0))], [((2, 0), (0, 1)), ((2, 1), (1, 1))], [((2, 0), (0, 2)), ((2, 1), (1, 2))]]
updates: [19, 22, 25, 43, 50, 57, 67, 78, 89]
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[19, 22, 25], [43, 50, 57], [67, 78, 89]]
Test 2 passed — uneven shapes (3x2) @ (2x3)
Indices: [[((0, 0), (0, 0)), ((0, 1), (1, 0)), ((0, 2), (2, 0))], [((0, 0), (0, 1)), ((0, 1), (1, 1)), ((0, 2), (2, 1))], [((1, 0), (0, 0)), ((1, 1), (1, 0)), ((1, 2), (2, 0))], [((1, 0), (0, 1)), ((1, 1), (1, 1)), ((1, 2),