## ReLU

$$f(x) = \max(0, x)$$

In [ ]:


def relu(x):
    return x if x>0 else 0

In [ ]:
relu(2)
relu([-2, -1, 0, 1, 2]) #fails here 

TypeError: '>' not supported between instances of 'list' and 'int'

##### To apply ReLU to matrix or array using NumPy maximum function is better

In [28]:
import numpy as np

def relu(z):
    return np.maximum(0,z)

In [29]:
print(relu(2))
print(relu(np.array([-2, -1, 0, 1, 2])))

2
[0 0 0 1 2]


## Leaky ReLU

$$f(x) = \begin{cases} x & \text{if } x > 0 \\ \alpha x & \text{if } x \leq 0 \end{cases}$$

In [30]:


def leaky_ReLU(z,leak=0.01):
    return np.maximum(leak*z,z)


In [31]:
print(leaky_ReLU(2))
print(leaky_ReLU(np.array([-2, -1, 0, 1, 2])))

2.0
[-0.02 -0.01  0.    1.    2.  ]


## ELU - exponential linear unit

$$f(x) = \begin{cases} x & \text{if } x > 0 \\ \alpha(e^x - 1) & \text{if } x \leq 0 \end{cases}$$

In [32]:
def elu(z,alpha=1):
    return np.where(z>0,z,alpha*(np.exp(z)-1))

In [33]:
print(elu(2))
print(elu(np.array([-2, -1, 0, 1, 2])))

2.0
[-0.86466472 -0.63212056  0.          1.          2.        ]


## scaled ELU

$$f(x) = \lambda \begin{cases} x & \text{if } x > 0 \\ \alpha(e^x - 1) & \text{if } x \leq 0 \end{cases}$$
$$\alpha \approx 1.6732, \quad \lambda \approx 1.0507$$

In [47]:
def selu(x, alpha=1.6732, lambda_=1.0507):
    return lambda_ * np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [45]:
print(selu(2))
print(selu(np.array([-2, -1, 0, 1, 2])))

2.1014
[-1.52010758 -1.11128769  0.          1.0507      2.1014    ]


## Gaussian Error Linear Unit (GELU)

$$f(x) = 0.5x\left(1 + \tanh\left(\sqrt{\frac{2}{\pi}}\left(x + 0.044715x^3\right)\right)\right)$$

In [40]:
def GeLU(z):
    return (0.5*z*(1+np.tanh(np.sqrt(2/np.pi)*(z+0.044715*z**3))))

In [41]:
print(GeLU(2))
print(GeLU(-2))
print(GeLU(np.array([-2, -1, 0, 1, 2])))

1.954597694087775
-0.04540230591222494
[-0.04540231 -0.15880801  0.          0.84119199  1.95459769]


## Swish

$$f(x) = \frac{x}{1 + e^{-\beta x}}$$
$$\beta = 1 \text{ (SiLU)}, \quad \beta = 1.702 \text{ (GELU approximation)}$$

In [51]:
def swish(z,beta = 1.702):
    return z*(1 / (1 + np.exp(-beta*z)))

In [53]:
print(swish(2))
print(swish(-2))
print(swish(np.array([-2, -1, 0, 1, 2])))

1.9356586231442083
-0.06434137685579186
[-0.06434138 -0.15420423  0.          0.84579577  1.93565862]


## Sigmoid

$$f(x) = \frac{1}{1 + e^{-x}}$$

In [54]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

## Tanh

$$f(x) = \tanh(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}$$

In [55]:
def tanh(z):
    return np.tanh(z)


## Softmax

$$f(x_i) = \frac{e^{x_i}}{\sum_{j=1}^{n} e^{x_j}}$$

In [ ]:
def softmax(z):
    return np.exp(z)/np.sum(np.exp(z))


In [58]:
print(softmax(np.array([-2, -1, 0, 1, 2])))

[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]


In [ ]:
softmax(np.array([1000, 2000, 3000]))  
# can't handle large numbers- overflows

/tmp/ipykernel_5310/456068719.py:2: RuntimeWarning: overflow encountered in exp
  return np.exp(z)/np.sum(np.exp(z))
/tmp/ipykernel_5310/456068719.py:2: RuntimeWarning: invalid value encountered in divide
  return np.exp(z)/np.sum(np.exp(z))


array([nan, nan, nan])

#### Numerically stable softmax :

$$f(x_i) = \frac{e^{x_i - \max(x)}}{\sum_{j=1}^{n} e^{x_j - \max(x)}}$$

In [ ]:
# Better implementation -> Subtract the max before exponentiating 
# More numerically stable implementation
def softmax(z):
    e_x = np.exp(z - np.max(z)) # Subtract the max from input before exponentiating 
    return e_x/np.sum(e_x)


In [60]:
softmax(np.array([1000, 2000, 3000]))  

array([0., 0., 1.])