In [33]:
import numpy as np

$$y = x*w \to y[i] = \sum_j x[i+j] . w[K-1-j]$$

w[K-1-j] means flipped kernel

K means length of kernel


In [34]:

def conv1d(x,w):
    """x is the signal and w is the kernel
    Assumes stride=1 and valid padding
    """
    x = np.array(x)
    w = np.array(w)
    flip_kernel = w[::-1].copy()
    n_conv = len(x)-len(w)+1
    res = np.zeros(n_conv)
    for i in range(n_conv):
        ans = x[i:len(w)+i] * flip_kernel
        res[i] = np.sum(ans)
    return res


In [35]:
x = [2,3,4]
w = [1,-1]
my_output = conv1d(x,w)
np_conv_output = np.convolve(x,w,mode="valid")

In [36]:
np.testing.assert_array_equal(actual=np_conv_output,desired=my_output)

In [37]:
x = [1,2,3,0,0]
w = [1,0,-1]
my_output = conv1d(x,w)
np_conv_output = np.convolve(x,w,mode="valid")

In [38]:
np.testing.assert_array_equal(actual=np_conv_output,desired=my_output)

In [39]:
my_output

array([ 2., -2., -3.])

In [40]:
np_conv_output

array([ 2, -2, -3])

$$y = x*w \to y[i] = \sum_j x[i+j] . w[j]$$

In [41]:

def cross_conv1d(x,w):
    """x is the signal and w is the kernel
    Assumes stride=1 and valid padding
    """
    x = np.array(x)
    w = np.array(w)
    # flip_kernel = w[::-1].copy() #! remove kernel flip
    n_conv = len(x)-len(w)+1
    res = np.zeros(n_conv)
    for i in range(n_conv):
        ans = x[i:len(w)+i] * w
        res[i] = np.sum(ans)
    return res


In [42]:
x = [2,3,4]
w = [1,-1]
my_output = cross_conv1d(x,w)
np_conv_output = np.correlate(x,w,mode="valid")
my_output,np_conv_output

(array([-1., -1.]), array([-1, -1]))